name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: elenasoshina/telegram-web-app-bot-node:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build_and_push
    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          script: |
            echo "${{ secrets.SSL_CERT }}" > /root/server.cert
            echo "${{ secrets.SSL_KEY }}" > /root/server.key
            chmod 600 /root/server.key /root/server.cert
            
            docker pull elenasoshina/telegram-web-app-bot-node:latest
            docker stop tg-bot-test || true
            docker rm tg-bot-test || true
            docker run -d --name tg-bot-test -p 8020:8020 \
              -v /root/server.key:/app/server.key \
              -v /root/server.cert:/app/server.cert \
              elenasoshina/telegram-web-app-bot-node:latest
